### ISSUE TITLE
Error starting weston-terminal

### ISSUE THREAD

**Issue by parsley42** [udevbe/greenfield#3]
I installed weston on Fedora 28, and updated the path in app-entries. Here's what I get:
```
Child 12809 launching /usr/bin/weston-terminal.
Wayland client connected.
Wayland client closed.
{ Error: Command failed: /usr/bin/weston-terminal
weston-terminal: clients/window.c:5152: window_create_internal: Assertion `custom || display->xdg_shell || display->ivi_application' failed.

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
  killed: false,
  code: null,
  signal: 'SIGABRT',
  cmd: '/usr/bin/weston-terminal',
  stdout: '',
  stderr: 'weston-terminal: clients/window.c:5152: window_create_internal: Assertion `custom || display->xdg_shell || display->ivi_application\' failed.\n' } 'Error: Command failed: /usr/bin/weston-terminal\nweston-terminal: clients/window.c:5152: window_create_internal: Assertion `custom || display->xdg_shell || display->ivi_application\' failed.\n\n    at ChildProcess.exithandler (child_process.js:275:12)\n    at emitTwo (events.js:126:13)\n    at ChildProcess.emit (events.js:214:7)\n    at maybeClose (internal/child_process.js:925:16)\n    at Socket.stream.socket.on (internal/child_process.js:346:11)\n    at emitOne (events.js:116:13)\n    at Socket.emit (events.js:211:7)\n    at Pipe._handle.close [as _onclose] (net.js:557:12)'
```

**Comment by Zubnix** [comment]
weston-terminal doesn't support xdg-shell stable protocol, but only the older pre-stable v6 xdg-shell. If you want something with a supported protocol, either use clients from weston 1.4 (very old, you'll have to compile it from weston git), or you can try installing gtk3 with version >=3.22.30 and launch eg. gtk3-demo, gnome-terminal, ...
